package: client
output: internal/client/client.gen.go
generate:
  client: true
  models: true
output-options:
  include-tags:
    - "Monitors"
    - "Monitor Stats"
    - "Alert Channels"
    - "Status Pages"
    - "Components"
    - "Disruptions"
    - "Webhooks"
